import { Subject } from './types'

export const SUBJECTS: Subject[] = [
  {
    slug: 'physiologic-optics',
    name: 'Physiologic Optics',
    description: 'Accommodation, refractive errors, schematic eye, visual physiology',
    color: 'teal',
    questionCount: 80,
    icon: '👁️',
    olePrep: true,
    hasExam: true,
  },
  {
    slug: 'binocular-vision',
    name: 'Binocular Vision',
    description: 'Vergence, eye movements, stereopsis, binocular disorders',
    color: 'blue',
    questionCount: 105,
    icon: '🎯',
    olePrep: true,
    hasExam: true,
  },
  {
    slug: 'theoretical-optics',
    name: 'Theoretical Optics',
    description: 'Geometric optics, lenses, prisms, optical principles',
    color: 'violet',
    questionCount: 71,
    icon: '🌈',
    olePrep: true,
    hasExam: true,
  },
  {
    slug: 'phorometry',
    name: 'Phorometry (21 Steps)',
    description: 'OEP 21-step sequence, probe bodies, phoria measurements',
    color: 'amber',
    questionCount: 113,
    icon: '🕶️',
    olePrep: true,
    hasExam: true,
  },
  {
    slug: 'primary-eye-care',
    name: 'Primary Eye Care',
    description: 'Case history, refraction, binocular vision, ocular disease, examination techniques',
    color: 'emerald',
    questionCount: 151,
    icon: '🩺',
    olePrep: true,
    hasExam: true,
  },
  {
    slug: 'ocular-anatomy',
    name: 'Ocular Anatomy',
    description: 'Orbit, eyelids, cornea, uvea, retina, visual pathways, cranial nerves, extraocular muscles',
    color: 'rose',
    questionCount: 63,
    icon: '🔬',
    olePrep: true,
    hasExam: true,
  },
  {
    slug: 'general-anatomy',
    name: 'General Anatomy',
    description: 'Cell biology, integumentary, skeletal, muscular, nervous, circulatory, respiratory, digestive systems',
    color: 'amber',
    questionCount: 104,
    icon: '🦴',
    olePrep: true,
    hasExam: true,
  },
  {
    slug: 'ocular-disease',
    name: 'Ocular Disease',
    description: 'Eyelid disorders, conjunctiva, cornea, uvea, glaucoma, retinal diseases, and neuro-ophthalmology.',
    color: 'red',
    questionCount: 106,
    icon: '🔴',
    olePrep: true,
    hasExam: true,
  },
  {
    slug: 'general-pharmacology',
    name: 'General Pharmacology',
    description: 'Pharmacokinetics, pharmacodynamics, ANS drugs, anti-infectives, CNS agents, and drug interactions.',
    color: 'indigo',
    questionCount: 102,
    icon: '💊',
    olePrep: true,
    hasExam: true,
  },
  {
    slug: 'ocular-pharmacology',
    name: 'Ocular Pharmacology',
    description: 'Diagnostic agents, anti-glaucoma drugs, anti-infectives, steroids, and autonomic agents in eye care.',
    color: 'cyan',
    questionCount: 104,
    icon: '👁️‍🗨️',
    olePrep: true,
    hasExam: true,
  },
  {
    slug: 'practical-mechanical-optics',
    name: 'Practical and Mechanical Optics',
    description: 'Lenses, prisms, optical instruments, retinoscopy, keratometry, and lens prescriptions.',
    color: 'lime',
    questionCount: 127,
    icon: '🔭',
    olePrep: true,
    hasExam: true,
  },
  {
    slug: 'optometry-constants',
    name: 'Optometry Constants',
    description: 'All key constants and formulas — Gullstrand\'s schematic eye, Hofstetter\'s, Prentice\'s Rule, cardinal points, and more.',
    color: 'gold',
    questionCount: 0,
    icon: '📐',
    olePrep: true,
    isBonus: true,
  },
  {
    slug: 'low-vision',
    name: 'Low Vision',
    description: 'Definitions and classification, colour vision, visual fields, contrast sensitivity, magnification, telescopes, reading adds, and low vision devices.',
    color: 'emerald',
    questionCount: 104,
    icon: '🔍',
    olePrep: true,
    hasExam: true,
  },
  {
    slug: 'pediatric-optometry',
    name: 'Pediatric Optometry',
    description: 'Visual development, primitive reflexes, pediatric exam and acuity tests, refraction, binocular vision, amblyopia, and childhood strabismus.',
    color: 'rose',
    questionCount: 102,
    icon: '🧸',
    olePrep: true,
    hasExam: true,
  },
  {
    slug: 'contact-lens',
    name: 'Contact Lens',
    description: 'Lens types and materials, oxygen performance, optics and formulas, tear assessment, soft and RGP fitting, fluorescein patterns, toric lenses, and lens care.',
    color: 'violet',
    questionCount: 106,
    icon: '🫧',
    olePrep: true,
    hasExam: true,
  },
  {
    slug: 'ethics-and-jurisprudence',
    name: 'Ethics and Jurisprudence',
    description: 'RA 8050 and its IRR, the Board of Optometry and PRC, licensure and registration, DPAs, CPD, professional practice, unlawful acts, ethics, malpractice, and practice management.',
    color: 'indigo',
    questionCount: 224,
    icon: '⚖️',
    olePrep: true,
    hasExam: true,
  },
]

// Subjects grouped by the 8 board areas of the optometry licensure exam
// (RA 8050 IRR / current PRC Program of Examination). `weight` is the area's
// percentage of the written (theoretical) exam. Drives the grouped home page.
export type SubjectGroup = { id: string; title: string; weight: number; slugs: string[] }

export const SUBJECT_GROUPS: SubjectGroup[] = [
  { id: 'visual-biology', title: 'Ocular & Visual Biology', weight: 10,
    slugs: ['ocular-anatomy', 'general-anatomy'] },
  { id: 'physio-bv', title: 'Physiological Optics, Binocular Vision & Perception', weight: 15,
    slugs: ['physiologic-optics', 'binocular-vision'] },
  { id: 'optics-dispensing', title: 'Theoretical, Practical Optics & Ophthalmic Dispensing', weight: 15,
    slugs: ['theoretical-optics', 'practical-mechanical-optics', 'contact-lens'] },
  { id: 'primary-care', title: 'Primary Care & Refraction', weight: 15,
    slugs: ['primary-eye-care', 'phorometry'] },
  { id: 'ocular-disease', title: 'Ocular Diseases & Ocular Emergencies', weight: 10,
    slugs: ['ocular-disease'] },
  { id: 'pharmacology', title: 'Ocular Pharmacology', weight: 10,
    slugs: ['ocular-pharmacology', 'general-pharmacology'] },
  { id: 'clinical-optometry', title: 'Clinical Optometry & Sub-Specialties', weight: 15,
    slugs: ['low-vision', 'pediatric-optometry'] },
  { id: 'ethics', title: 'Ethics, Jurisprudence, Practice Management & Public Health', weight: 10,
    slugs: ['ethics-and-jurisprudence'] },
]

export const COLOR_MAP: Record<string, {
  bg: string
  border: string
  badge: string
  text: string
  gradient: string
  progressBar: string
  ring: string
}> = {
  teal: {
    bg: 'bg-teal-50',
    border: 'border-teal-200',
    badge: 'bg-teal-100 text-teal-800',
    text: 'text-teal-700',
    gradient: 'from-teal-500 to-emerald-600',
    progressBar: 'bg-teal-500',
    ring: '#14b8a6',
  },
  blue: {
    bg: 'bg-blue-50',
    border: 'border-blue-200',
    badge: 'bg-blue-100 text-blue-800',
    text: 'text-blue-700',
    gradient: 'from-blue-500 to-indigo-600',
    progressBar: 'bg-blue-500',
    ring: '#3b82f6',
  },
  violet: {
    bg: 'bg-violet-50',
    border: 'border-violet-200',
    badge: 'bg-violet-100 text-violet-800',
    text: 'text-violet-700',
    gradient: 'from-violet-500 to-purple-600',
    progressBar: 'bg-violet-500',
    ring: '#8b5cf6',
  },
  amber: {
    bg: 'bg-amber-50',
    border: 'border-amber-200',
    badge: 'bg-amber-100 text-amber-800',
    text: 'text-amber-700',
    gradient: 'from-amber-400 to-orange-500',
    progressBar: 'bg-amber-500',
    ring: '#f59e0b',
  },
  emerald: {
    bg: 'bg-emerald-50',
    border: 'border-emerald-200',
    badge: 'bg-emerald-100 text-emerald-800',
    text: 'text-emerald-700',
    gradient: 'from-emerald-500 to-teal-600',
    progressBar: 'bg-emerald-500',
    ring: '#10b981',
  },
  rose: {
    bg: 'bg-rose-50',
    border: 'border-rose-200',
    badge: 'bg-rose-100 text-rose-800',
    text: 'text-rose-700',
    gradient: 'from-rose-500 to-pink-600',
    progressBar: 'bg-rose-500',
    ring: '#f43f5e',
  },
  red: {
    bg: 'bg-red-50',
    border: 'border-red-200',
    badge: 'bg-red-100 text-red-800',
    text: 'text-red-700',
    gradient: 'from-red-500 to-rose-600',
    progressBar: 'bg-red-500',
    ring: '#ef4444',
  },
  indigo: {
    bg: 'bg-indigo-50',
    border: 'border-indigo-200',
    badge: 'bg-indigo-100 text-indigo-800',
    text: 'text-indigo-700',
    gradient: 'from-indigo-500 to-indigo-700',
    progressBar: 'bg-indigo-500',
    ring: '#6366f1',
  },
  cyan: {
    bg: 'bg-cyan-50',
    border: 'border-cyan-200',
    badge: 'bg-cyan-100 text-cyan-800',
    text: 'text-cyan-700',
    gradient: 'from-cyan-500 to-cyan-700',
    progressBar: 'bg-cyan-500',
    ring: '#06b6d4',
  },
  lime: {
    bg: 'bg-lime-50',
    border: 'border-lime-200',
    badge: 'bg-lime-100 text-lime-800',
    text: 'text-lime-700',
    gradient: 'from-lime-500 to-lime-700',
    progressBar: 'bg-lime-500',
    ring: '#84cc16',
  },
  gold: {
    bg: 'bg-yellow-50',
    border: 'border-yellow-300',
    badge: 'bg-yellow-100 text-yellow-800',
    text: 'text-yellow-700',
    gradient: 'from-yellow-400 to-amber-500',
    progressBar: 'bg-yellow-500',
    ring: '#eab308',
  },
}
