// Backfill the main-app JSON banks into a seed for public.questions.
//
// Reads the 14 WIRED banks in src/data/*.json (every slug in banks.ts QUESTION_MAP
// except ocular-anatomy, which the app serves from a notes-quiz .ts, not its .json).
// Emits INSERT statements to stdout and a coverage/dup report to stderr.
//
// stem_hash is computed byte-for-byte the same as src/lib/srs.ts questionId(), so the
// seeded rows line up with the existing question_reviews / daily_queue rows.
//
//   node exam-build/backfill_questions.mjs > /tmp/questions_seed.sql
//
// Nothing here touches Supabase. It only reads local JSON and writes SQL text.

import { readFileSync, readdirSync } from 'node:fs'
import { join, basename } from 'node:path'

const DATA_DIR = join(process.cwd(), 'src', 'data')
const SKIP = new Set(['ocular-anatomy']) // served from notes-quiz .ts, handled separately

// --- exact copy of src/lib/srs.ts, so hashes match the running app -----------------
function normalizeStem(stem) {
  return stem
    .toLowerCase()
    .replace(/[‘’]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()
}
function questionId(stem) {
  const s = normalizeStem(stem)
  let h = 0x811c9dc5
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i)
    h = Math.imul(h, 0x01000193) >>> 0
  }
  return h.toString(16).padStart(8, '0') + '-' + s.length.toString(36)
}
// -----------------------------------------------------------------------------------

// SQL literal helpers. Single-quote escaping only; no interpolation of untrusted shell input.
const sqlStr = (v) => (v === null || v === undefined ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`)
const sqlJson = (v) => (v === null || v === undefined ? 'NULL' : `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`)
const sqlBool = (v) => (v ? 'true' : 'false')

const files = readdirSync(DATA_DIR)
  .filter((f) => f.endsWith('.json'))
  .map((f) => basename(f, '.json'))
  .filter((slug) => !SKIP.has(slug))
  .sort()

const rows = []
const report = []
const seenHash = new Map() // stem_hash -> [ "subject#index", ... ] to surface duplicates

let total = 0
for (const slug of files) {
  const arr = JSON.parse(readFileSync(join(DATA_DIR, `${slug}.json`), 'utf8'))
  let mcq = 0
  let tf = 0
  arr.forEach((q, i) => {
    const type = q.type === 'tf' ? 'tf' : 'mcq'
    const hash = questionId(q.stem)
    const where = `${slug}#${i}`
    if (seenHash.has(hash)) seenHash.get(hash).push(where)
    else seenHash.set(hash, [where])

    rows.push({
      stem_hash: hash,
      type,
      stem: q.stem,
      options: type === 'mcq' ? q.options ?? [] : null,
      correct: type === 'tf' ? Boolean(q.correct) : Number(q.correct),
      explanation: q.explanation ?? null,
      subject: slug,
      subtopic: q.category ?? null,
      section_code: q.module ?? null,
      is_trap: Boolean(q.isTrap),
      source: 'bank',
      origin_file: `src/data/${slug}.json`,
    })
    if (type === 'tf') tf++
    else mcq++
  })
  total += arr.length
  report.push(`${String(arr.length).padStart(4)}  ${slug}  (mcq ${mcq}, tf ${tf})`)
}

// --- emit the seed SQL to stdout ---------------------------------------------------
const cols = [
  'stem_hash', 'type', 'stem', 'options', 'correct', 'explanation',
  'subject', 'subtopic', 'section_code', 'is_trap', 'source', 'origin_file',
]
process.stdout.write(`-- Generated by exam-build/backfill_questions.mjs — ${new Date().toISOString()}\n`)
process.stdout.write(`-- ${rows.length} rows from ${files.length} wired main-app banks. Run AFTER questions-table.sql.\n`)
process.stdout.write(`insert into public.questions (${cols.join(', ')}) values\n`)
const values = rows.map((r) =>
  `  (${sqlStr(r.stem_hash)}, ${sqlStr(r.type)}, ${sqlStr(r.stem)}, ${sqlJson(r.options)}, ` +
  `${sqlJson(r.correct)}, ${sqlStr(r.explanation)}, ${sqlStr(r.subject)}, ${sqlStr(r.subtopic)}, ` +
  `${sqlStr(r.section_code)}, ${sqlBool(r.is_trap)}, ${sqlStr(r.source)}, ${sqlStr(r.origin_file)})`
)
process.stdout.write(values.join(',\n') + ';\n')

// --- coverage + dup report to stderr ----------------------------------------------
const dups = [...seenHash.entries()].filter(([, w]) => w.length > 1)
process.stderr.write('\n=== Per-bank counts ===\n' + report.join('\n') + '\n')
process.stderr.write(`\nTOTAL rows: ${rows.length}  (banks: ${files.length})\n`)
process.stderr.write(`Distinct stem_hash: ${seenHash.size}\n`)
process.stderr.write(`Duplicate stem_hash groups: ${dups.length}\n`)
if (dups.length) {
  process.stderr.write('  (same normalized stem appearing more than once — reconcile deliberately)\n')
  dups.slice(0, 20).forEach(([h, w]) => process.stderr.write(`  ${h}  ->  ${w.join(', ')}\n`))
  if (dups.length > 20) process.stderr.write(`  ... and ${dups.length - 20} more\n`)
}
